### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by simensen** [matthiasnoback/naive-serializer#4]
I'm curious about the performance impact of creating a new instance of `JsonSerializer` for each action. If someone is going to be handling a lot of objects (say, a specific event stream or reprocessing *all* events from an event store), it seems like this could become a performance bottleneck.

Am I overthinking it? Is there magic in how phpDocumentor does things that make this a non-issue?

**Comment by matthiasnoback** [comment]
This is why the library offers a static helper (which creates a new instance for one-off use: `Serializer`), and a regular service that can be instantiated and reused (`JsonSerializer`). I didn't look into performance.
Regarding phpDocumentor: it may have some caching mechanism, but I didn't look into the internals either. This library has only been used (by me) in workshops.

**Comment by simensen** [comment]
Silly me. :) I could have *sworn* when I was looking at this earlier they were both implementing the same interface. Or any interface. Clearly I wasn't paying nearly enough attention. :) I was actually looking at the `Serializer` and now understanding that I should just use `JsonSerializer` outright and ignore `Serializer` for my purposes.

**Comment by matthiasnoback** [comment]
No problem! Let me know if you find it useful (or find any issues with it!).
